name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install node modules
      run: npm install
    - name: Execute static security tests
      run: npm audit
    - name: Execute integration tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'refs/heads/main'
    
    # steps:
    #   - name: Deploy to production
    #     uses: johnbeynon/render-deploy-action@v0.0.8
    #     with:
    #       service-id: ${{ secrets.MY_RENDER_SERVICE_ID }} # e.g. srv-abcde
    #       api-key: ${{ secrets.MY_RENDER_API_KEY }} # e.g. render-abcde
    # alternative
    steps:
    - uses: JorgeLNJunior/render-deploy@v1.4.5
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}
        wait_deploy: true